/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by LCM
 **/

#include <string.h>
#include "lcmtypes_laser_t.h"

static int __lcmtypes_laser_t_hash_computed;
static int64_t __lcmtypes_laser_t_hash;
 
int64_t __lcmtypes_laser_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __lcmtypes_laser_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__lcmtypes_laser_t_get_hash };
    (void) cp;
 
    int64_t hash = 0xf1e8ba118c05af46LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __lcmtypes_laser_t_get_hash(void)
{
    if (!__lcmtypes_laser_t_hash_computed) {
        __lcmtypes_laser_t_hash = __lcmtypes_laser_t_hash_recursive(NULL);
        __lcmtypes_laser_t_hash_computed = 1;
    }
 
    return __lcmtypes_laser_t_hash;
}
 
int __lcmtypes_laser_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_laser_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].nranges);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nintensities), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].nintensities);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rad0), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].radstep), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int lcmtypes_laser_t_encode(void *buf, int offset, int maxlen, const lcmtypes_laser_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmtypes_laser_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __lcmtypes_laser_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __lcmtypes_laser_t_encoded_array_size(const lcmtypes_laser_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __int64_t_encoded_array_size(&(p[element].utime), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].nranges), 1);
 
        size += __float_encoded_array_size(p[element].ranges, p[element].nranges);
 
        size += __int32_t_encoded_array_size(&(p[element].nintensities), 1);
 
        size += __float_encoded_array_size(p[element].intensities, p[element].nintensities);
 
        size += __float_encoded_array_size(&(p[element].rad0), 1);
 
        size += __float_encoded_array_size(&(p[element].radstep), 1);
 
    }
    return size;
}
 
int lcmtypes_laser_t_encoded_size(const lcmtypes_laser_t *p)
{
    return 8 + __lcmtypes_laser_t_encoded_array_size(p, 1);
}
 
int __lcmtypes_laser_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_laser_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nranges), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].ranges = (float*) lcm_malloc(sizeof(float) * p[element].nranges);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].ranges, p[element].nranges);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nintensities), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].intensities = (float*) lcm_malloc(sizeof(float) * p[element].nintensities);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].intensities, p[element].nintensities);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rad0), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].radstep), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __lcmtypes_laser_t_decode_array_cleanup(lcmtypes_laser_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_decode_array_cleanup(&(p[element].utime), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].nranges), 1);
 
        __float_decode_array_cleanup(p[element].ranges, p[element].nranges);
        if (p[element].ranges) free(p[element].ranges);
 
        __int32_t_decode_array_cleanup(&(p[element].nintensities), 1);
 
        __float_decode_array_cleanup(p[element].intensities, p[element].nintensities);
        if (p[element].intensities) free(p[element].intensities);
 
        __float_decode_array_cleanup(&(p[element].rad0), 1);
 
        __float_decode_array_cleanup(&(p[element].radstep), 1);
 
    }
    return 0;
}
 
int lcmtypes_laser_t_decode(const void *buf, int offset, int maxlen, lcmtypes_laser_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __lcmtypes_laser_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __lcmtypes_laser_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int lcmtypes_laser_t_decode_cleanup(lcmtypes_laser_t *p)
{
    return __lcmtypes_laser_t_decode_array_cleanup(p, 1);
}
 
int __lcmtypes_laser_t_clone_array(const lcmtypes_laser_t *p, lcmtypes_laser_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);
 
        __int32_t_clone_array(&(p[element].nranges), &(q[element].nranges), 1);
 
        q[element].ranges = (float*) lcm_malloc(sizeof(float) * q[element].nranges);
        __float_clone_array(p[element].ranges, q[element].ranges, p[element].nranges);
 
        __int32_t_clone_array(&(p[element].nintensities), &(q[element].nintensities), 1);
 
        q[element].intensities = (float*) lcm_malloc(sizeof(float) * q[element].nintensities);
        __float_clone_array(p[element].intensities, q[element].intensities, p[element].nintensities);
 
        __float_clone_array(&(p[element].rad0), &(q[element].rad0), 1);
 
        __float_clone_array(&(p[element].radstep), &(q[element].radstep), 1);
 
    }
    return 0;
}
 
lcmtypes_laser_t *lcmtypes_laser_t_copy(const lcmtypes_laser_t *p)
{
    lcmtypes_laser_t *q = (lcmtypes_laser_t*) malloc(sizeof(lcmtypes_laser_t));
    __lcmtypes_laser_t_clone_array(p, q, 1);
    return q;
}
 
void lcmtypes_laser_t_destroy(lcmtypes_laser_t *p)
{
    __lcmtypes_laser_t_decode_array_cleanup(p, 1);
    free(p);
}
