/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by LCM
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _lcmtypes_gps_to_local_t_h
#define _lcmtypes_gps_to_local_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmtypes_gps_to_local_t lcmtypes_gps_to_local_t;
struct _lcmtypes_gps_to_local_t
{
    int64_t    utime;
    double     local[3];
    double     lat_lon_el_theta[4];
    float      gps_cov[4][4];
};
 
lcmtypes_gps_to_local_t   *lcmtypes_gps_to_local_t_copy(const lcmtypes_gps_to_local_t *p);
void lcmtypes_gps_to_local_t_destroy(lcmtypes_gps_to_local_t *p);

int  lcmtypes_gps_to_local_t_encode(void *buf, int offset, int maxlen, const lcmtypes_gps_to_local_t *p);
int  lcmtypes_gps_to_local_t_decode(const void *buf, int offset, int maxlen, lcmtypes_gps_to_local_t *p);
int  lcmtypes_gps_to_local_t_decode_cleanup(lcmtypes_gps_to_local_t *p);
int  lcmtypes_gps_to_local_t_encoded_size(const lcmtypes_gps_to_local_t *p);

// LCM support functions. Users should not call these
int64_t __lcmtypes_gps_to_local_t_get_hash(void);
int64_t __lcmtypes_gps_to_local_t_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmtypes_gps_to_local_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_gps_to_local_t *p, int elements);
int     __lcmtypes_gps_to_local_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_gps_to_local_t *p, int elements);
int     __lcmtypes_gps_to_local_t_decode_array_cleanup(lcmtypes_gps_to_local_t *p, int elements);
int     __lcmtypes_gps_to_local_t_encoded_array_size(const lcmtypes_gps_to_local_t *p, int elements);
int     __lcmtypes_gps_to_local_t_clone_array(const lcmtypes_gps_to_local_t *p, lcmtypes_gps_to_local_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
