/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by LCM
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm_coretypes.h"

#ifndef _lcmtypes_laser_t_h
#define _lcmtypes_laser_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmtypes_laser_t lcmtypes_laser_t;
struct _lcmtypes_laser_t
{
    int64_t    utime;
    int32_t    nranges;
    float      *ranges;
    int32_t    nintensities;
    float      *intensities;
    float      rad0;
    float      radstep;
};
 
lcmtypes_laser_t   *lcmtypes_laser_t_copy(const lcmtypes_laser_t *p);
void lcmtypes_laser_t_destroy(lcmtypes_laser_t *p);

int  lcmtypes_laser_t_encode(void *buf, int offset, int maxlen, const lcmtypes_laser_t *p);
int  lcmtypes_laser_t_decode(const void *buf, int offset, int maxlen, lcmtypes_laser_t *p);
int  lcmtypes_laser_t_decode_cleanup(lcmtypes_laser_t *p);
int  lcmtypes_laser_t_encoded_size(const lcmtypes_laser_t *p);

// LCM support functions. Users should not call these
int64_t __lcmtypes_laser_t_get_hash(void);
int64_t __lcmtypes_laser_t_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmtypes_laser_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_laser_t *p, int elements);
int     __lcmtypes_laser_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_laser_t *p, int elements);
int     __lcmtypes_laser_t_decode_array_cleanup(lcmtypes_laser_t *p, int elements);
int     __lcmtypes_laser_t_encoded_array_size(const lcmtypes_laser_t *p, int elements);
int     __lcmtypes_laser_t_clone_array(const lcmtypes_laser_t *p, lcmtypes_laser_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
